databases:
  - name: dikdik-urlaubsapp-db
    plan: free
    databaseName: dikdik
    user: dikdik

services:
  - type: web
    name: dikdik-urlaubsapp-web
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dikdik-urlaubsapp-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: TRIP_CODE
        sync: false
      - key: TRIP_NAME
        sync: false
      - key: TRIP_START_DATE
        sync: false
      - key: TRIP_END_DATE
        sync: false
